# Load the packages
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(testthat))
suppressPackageStartupMessages(library(tidymodels))
suppressPackageStartupMessages(library(yardstick))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(pROC))
suppressPackageStartupMessages(library(DALEXtra))

suppressPackageStartupMessages(library(here))
suppressPackageStartupMessages(library(roxygen2))
suppressPackageStartupMessages(library(openxlsx))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(tidymodels))
suppressPackageStartupMessages(library(vip))
suppressPackageStartupMessages(library(ranger))
suppressPackageStartupMessages(library(lightgbm))
suppressPackageStartupMessages(library(bonsai))
suppressPackageStartupMessages(library(xgboost))
suppressPackageStartupMessages(library(DataExplorer))
suppressPackageStartupMessages(library(DALEXtra))
