# install.packages('renv')
# renv::init()
# renv::activate()

renv::install("tidymodels")
#renv::install("tidyverse")
renv::install("openxlsx")
renv::install("ggplot2")
renv::install("here")
renv::install("testthat")
renv::install("plotly")
renv::install("speff2trial")
renv::install("tidymodels/censored")
renv::install("gridExtra")
renv::install("survminer")
renv::install("glue")
renv::install("ranger")
renv::install("xgboost")
renv::install("readxl")
renv::install("DT")
renv::install("diffobj")
renv::install("plotly")
renv::install("pROC")
renv::install("parallelly")
renv::install("parallel")
renv::install("doParallel")
renv::install("recipes")
renv::install("themis")
renv::install("DALEXtra")
renv::install("daroczig/logger")
renv::install("glmnet")
#renv::install("")
#renv::install("")
#renv::install("")
#renv::install("")



renv::status()

renv::snapshot()

renv::status()
